import React, { useState } from 'react';
import { Link } from 'react-router-dom';
import { motion } from 'framer-motion';
import { useAuth } from '../context/AuthContext.jsx';
import { 
  Sprout, 
  CloudSun, 
  TrendingUp, 
  ShieldCheck, 
  MapPin, 
  ArrowRight,
  Phone,
  Mail,
  UserCheck,
  BrainCircuit,
  Coins,
  Warehouse,
  Sparkles,
  Award
} from 'lucide-react';
import { Button } from '../components/ui/button.jsx';
import { Card } from '../components/ui/card.jsx';

// Import local real images generated by Gemini
import heroBg from '../assets/hero_bg.png';
import scannerImg from '../assets/scanner.png';
import marketImg from '../assets/market.png';
import logoImg from '../assets/logo.png';

export default function Landing() {
  const { user, token } = useAuth();
  const [contactForm, setContactForm] = useState({ name: '', email: '', message: '' });
  const [submitted, setSubmitted] = useState(false);

  const handleSubmit = (e) => {
    e.preventDefault();
    setSubmitted(true);
    setContactForm({ name: '', email: '', message: '' });
    setTimeout(() => setSubmitted(false), 4000);
  };

  const containerVariants = {
    hidden: { opacity: 0 },
    visible: {
      opacity: 1,
      transition: { staggerChildren: 0.15 }
    }
  };

  const itemVariants = {
    hidden: { opacity: 0, y: 30 },
    visible: { opacity: 1, y: 0, transition: { duration: 0.5, ease: 'easeOut' } }
  };

  return (
    <div className="min-h-screen bg-slate-50 font-sans text-slate-900 scroll-smooth overflow-x-hidden">
      {/* Navbar */}
      <header className="sticky top-0 z-50 glass-panel border-b border-slate-200 px-6 py-4 flex items-center justify-between">
        <div className="flex items-center gap-2">
          <img src={logoImg} alt="KrishiSakhi Logo" className="h-9 w-9 rounded-lg object-cover shadow-md shadow-green-150" />
          <span className="text-xl font-bold tracking-tight text-slate-800">
            Krishi<span className="text-green-600">Sakhi</span>
          </span>
        </div>
        
        <nav className="hidden md:flex items-center gap-6 text-sm font-semibold text-slate-600">
          <a href="#about" className="hover:text-green-600 transition">About</a>
          <a href="#features" className="hover:text-green-600 transition">Features</a>
          <a href="#disease-spotlight" className="hover:text-green-600 transition">AI Diagnostics</a>
          <a href="#market-spotlight" className="hover:text-green-600 transition">Market Pricing</a>
          <a href="#contact" className="hover:text-green-600 transition">Contact</a>
        </nav>

        <div className="flex items-center gap-3">
          {token && user ? (
            <Link to={user.role === 'admin' ? '/admin' : '/dashboard'}>
              <Button variant="primary" size="sm" className="flex items-center gap-1.5 font-bold shadow-md shadow-green-100">
                Go to Dashboard <ArrowRight size={14} />
              </Button>
            </Link>
          ) : (
            <>
              <Link to="/login">
                <Button variant="outline" size="sm">Login</Button>
              </Link>
              <Link to="/register">
                <Button variant="primary" size="sm">Register</Button>
              </Link>
            </>
          )}
        </div>
      </header>

      {/* Hero Section */}
      <section className="relative px-6 py-16 md:py-24 max-w-6xl mx-auto grid md:grid-cols-2 gap-12 items-center overflow-hidden">
        <motion.div 
          initial={{ opacity: 0, x: -50 }}
          animate={{ opacity: 1, x: 0 }}
          transition={{ duration: 0.6, ease: 'easeOut' }}
          className="space-y-6 text-left"
        >
          <div className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full bg-green-150 text-green-800 text-xs font-bold uppercase tracking-wide">
            <Sparkles size={14} className="text-yellow-500 animate-pulse" /> Precision Crop Advisory
          </div>
          <h1 className="text-4xl md:text-5xl font-black tracking-tight text-slate-900 leading-tight">
            Cultivate Smarter. <br />
            Sell Smarter with <span className="text-green-600">AI Intelligence</span>
          </h1>
          <p className="text-base text-slate-600 leading-relaxed">
            KrishiSakhi helps smallholder farmers maximize crop yields, detect plant leaf disease patterns in seconds, and run comparative financial decisions to optimize storage rent and transit logistics.
          </p>
          <div className="flex flex-wrap gap-4 pt-2">
            <Link to="/register">
              <Button size="lg" className="h-12 px-8 flex items-center gap-2 font-bold shadow-lg shadow-green-100">
                Get Started Free <ArrowRight size={18} />
              </Button>
            </Link>
            <a href="#features">
              <Button variant="outline" size="lg" className="h-12 px-8 font-semibold">
                Explore Features
              </Button>
            </a>
          </div>
        </motion.div>

        {/* Hero image preview with overlays */}
        <motion.div 
          initial={{ opacity: 0, scale: 0.95, x: 55 }}
          animate={{ opacity: 1, scale: 1, x: 0 }}
          transition={{ duration: 0.7, ease: 'easeOut' }}
          className="relative flex justify-center"
        >
          <div className="relative rounded-2xl overflow-hidden shadow-2xl border-4 border-white max-w-[480px]">
            <img src={heroBg} alt="Smart Farming fields" className="w-full h-auto object-cover aspect-4/3" />
            
            {/* Visual overlay tag */}
            <div className="absolute bottom-4 left-4 bg-slate-900/80 backdrop-blur px-3 py-1.5 rounded-lg text-white text-xs font-semibold flex items-center gap-1.5">
              <Sprout size={14} className="text-green-400" />
              <span>AI Crop Advisory Active</span>
            </div>
          </div>
          
          {/* Floating UI Badges */}
          <motion.div 
            animate={{ y: [0, -10, 0] }}
            transition={{ repeat: Infinity, duration: 4, ease: "easeInOut" }}
            className="absolute -top-4 right-4 bg-white shadow-xl rounded-xl p-3 border border-slate-100 flex items-center gap-2 text-left"
          >
            <div className="h-8 w-8 rounded-lg bg-green-50 text-green-600 flex items-center justify-center font-bold">
              +24%
            </div>
            <div>
              <p className="text-[10px] text-slate-400 font-bold uppercase">Estimated Yield Increase</p>
              <p className="text-xs font-black text-slate-800">Precision Soil NPK</p>
            </div>
          </motion.div>
        </motion.div>
      </section>

      {/* About Us */}
      <section id="about" className="py-20 bg-white border-y border-slate-200 px-6">
        <div className="max-w-5xl mx-auto grid md:grid-cols-2 gap-12 items-center">
          <div className="space-y-6 text-left">
            <h2 className="text-3xl font-black tracking-tight text-slate-800">About KrishiSakhi</h2>
            <p className="text-slate-600 leading-relaxed text-sm">
              Smallholder farmers manage over 80% of farmland across developing regions but face significant hurdles: lack of weather transparency, delayed pest alerts, and post-harvest spoilage risks. 
            </p>
            <p className="text-slate-600 leading-relaxed text-sm">
              KrishiSakhi provides a full-stack, data-driven agricultural decision network. By inputting farm metrics and local coordinates, farmers receive precise chemical schedules, leaf diagnostics, and transit calculations to minimize losses and maximize profit margins.
            </p>
          </div>
          <div className="bg-gradient-to-tr from-green-600 to-lime-500 rounded-2xl p-6 text-white text-left space-y-4 shadow-xl">
            <h3 className="text-xl font-extrabold">Why Choose Our Platform?</h3>
            <ul className="space-y-3 text-xs leading-normal">
              <li className="flex items-start gap-2">
                <span className="h-2 w-2 rounded-full bg-lime-300 mt-1.5 flex-shrink-0" />
                <span><strong className="font-extrabold text-lime-100">Auto weather alerts</strong> that postpone irrigation before high rain, saving fuel and pump wear.</span>
              </li>
              <li className="flex items-start gap-2">
                <span className="h-2 w-2 rounded-full bg-lime-300 mt-1.5 flex-shrink-0" />
                <span><strong className="font-extrabold text-lime-100">Precision chemical models</strong> matching soil types to target Nitrogen deficiencies.</span>
              </li>
              <li className="flex items-start gap-2">
                <span className="h-2 w-2 rounded-full bg-lime-300 mt-1.5 flex-shrink-0" />
                <span><strong className="font-extrabold text-lime-100">Freight cost analysis</strong> that compares distant mandi price premiums against transit rates.</span>
              </li>
            </ul>
          </div>
        </div>
      </section>

      {/* Features Grid - fixed padding margins */}
      <section id="features" className="py-20 px-6 max-w-6xl mx-auto space-y-12">
        <div className="text-center space-y-4">
          <h2 className="text-3xl font-black tracking-tight text-slate-800">Platform Core Pillars</h2>
          <p className="text-slate-500 max-w-xl mx-auto text-sm">Everything a farmer needs to grow healthier crops and sell for higher prices.</p>
        </div>

        <motion.div 
          variants={containerVariants}
          initial="hidden"
          whileInView="visible"
          viewport={{ once: true, margin: "-100px" }}
          className="grid sm:grid-cols-2 lg:grid-cols-3 gap-6"
        >
          {/* Card 1: AI Advisory */}
          <motion.div variants={itemVariants}>
            <Card className="p-6 hover-scale space-y-4 bg-white border border-slate-200 shadow-sm relative overflow-hidden transition-all duration-200 text-left h-full">
              <div className="h-10 w-10 flex items-center justify-center rounded-lg bg-green-150 text-green-700">
                <BrainCircuit size={20} />
              </div>
              <h3 className="text-lg font-bold text-slate-800">AI Crop Advisory</h3>
              <p className="text-xs text-slate-500 leading-relaxed">
                Precision fertilizer guidelines and irrigation alerts based on current growth stage and soil metrics.
              </p>
            </Card>
          </motion.div>

          {/* Card 2: Disease Scanner */}
          <motion.div variants={itemVariants}>
            <Card className="p-6 hover-scale space-y-4 bg-white border border-slate-200 shadow-sm relative overflow-hidden transition-all duration-200 text-left h-full">
              <div className="h-10 w-10 flex items-center justify-center rounded-lg bg-teal-100 text-teal-700">
                <ShieldCheck size={20} />
              </div>
              <h3 className="text-lg font-bold text-slate-800">Disease Detection</h3>
              <p className="text-xs text-slate-500 leading-relaxed">
                Upload leaf photographs to diagnose crop conditions instantly and retrieve exact organic and chemical treatments.
              </p>
            </Card>
          </motion.div>

          {/* Card 3: Weather */}
          <motion.div variants={itemVariants}>
            <Card className="p-6 hover-scale space-y-4 bg-white border border-slate-200 shadow-sm relative overflow-hidden transition-all duration-200 text-left h-full">
              <div className="h-10 w-10 flex items-center justify-center rounded-lg bg-yellow-100 text-yellow-700">
                <CloudSun size={20} />
              </div>
              <h3 className="text-lg font-bold text-slate-800">Weather Intelligence</h3>
              <p className="text-xs text-slate-500 leading-relaxed">
                7-day localized rain forecast and alert monitors advising whether to accelerate or postpone watering.
              </p>
            </Card>
          </motion.div>

          {/* Card 4: Market Prices */}
          <motion.div variants={itemVariants}>
            <Card className="p-6 hover-scale space-y-4 bg-white border border-slate-200 shadow-sm relative overflow-hidden transition-all duration-200 text-left h-full">
              <div className="h-10 w-10 flex items-center justify-center rounded-lg bg-amber-100 text-amber-700">
                <TrendingUp size={20} />
              </div>
              <h3 className="text-lg font-bold text-slate-800">Market Intelligence</h3>
              <p className="text-xs text-slate-500 leading-relaxed">
                Check active mandi pricing across nearby districts and configure triggers to alert you when target values are reached.
              </p>
            </Card>
          </motion.div>

          {/* Card 5: Post-harvest Engine */}
          <motion.div variants={itemVariants}>
            <Card className="p-6 hover-scale space-y-4 bg-white border border-slate-200 shadow-sm relative overflow-hidden transition-all duration-200 text-left h-full">
              <div className="h-10 w-10 flex items-center justify-center rounded-lg bg-lime-150 text-lime-800">
                <Coins size={20} />
              </div>
              <h3 className="text-lg font-bold text-slate-800">Post-Harvest Decision Engine</h3>
              <p className="text-xs text-slate-500 leading-relaxed">
                Compare profits across options: sell immediately, transport to regional mandis, or rent cold storage.
              </p>
            </Card>
          </motion.div>

          {/* Card 6: Farm Location */}
          <motion.div variants={itemVariants}>
            <Card className="p-6 hover-scale space-y-4 bg-white border border-slate-200 shadow-sm relative overflow-hidden transition-all duration-200 text-left h-full">
              <div className="h-10 w-10 flex items-center justify-center rounded-lg bg-blue-100 text-blue-700">
                <MapPin size={20} />
              </div>
              <h3 className="text-lg font-bold text-slate-800">Farm Location & Soil</h3>
              <p className="text-xs text-slate-500 leading-relaxed">
                Add multiple farms with custom sizes and coordinate mapping to retrieve location-specific soil recommendations.
              </p>
            </Card>
          </motion.div>
        </motion.div>
      </section>

      {/* Disease Spotlight - with real scannerImg */}
      <section id="disease-spotlight" className="py-20 bg-white border-y border-slate-200 px-6">
        <div className="max-w-5xl mx-auto grid md:grid-cols-12 gap-12 items-center">
          <motion.div 
            initial={{ opacity: 0, x: -40 }}
            whileInView={{ opacity: 1, x: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.6 }}
            className="md:col-span-5 flex justify-center"
          >
            <div className="relative rounded-2xl overflow-hidden shadow-2xl border-4 border-slate-50 max-w-[340px]">
              <img src={scannerImg} alt="Leaf Scanner Tool" className="w-full h-auto object-cover aspect-3/4" />
            </div>
          </motion.div>

          <motion.div 
            initial={{ opacity: 0, x: 40 }}
            whileInView={{ opacity: 1, x: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.6 }}
            className="md:col-span-7 space-y-6 text-left"
          >
            <div className="h-9 w-9 rounded-lg bg-teal-50 text-teal-700 flex items-center justify-center">
              <ShieldCheck size={18} />
            </div>
            <h3 className="text-2xl md:text-3xl font-extrabold text-slate-800">Instant AI Leaf Diagnostics</h3>
            <p className="text-slate-600 text-sm leading-relaxed">
              Pest damage and fungal infections propagate rapidly, wiping out harvests in days. 
            </p>
            <p className="text-slate-600 text-sm leading-relaxed">
              With KrishiSakhi's Disease Scanner, capture a photo of the affected plant leaf. Our neural classification model identifies disease signatures like Yellow Rust, Brown Spot, or late blights, returning the exact organic and chemical treatments to execute immediately.
            </p>
            <Link to="/register" className="inline-flex">
              <Button className="flex items-center gap-2">Try Disease Scanner <ArrowRight size={14} /></Button>
            </Link>
          </motion.div>
        </div>
      </section>

      {/* Market Pricing Spotlight - with real marketImg */}
      <section id="market-spotlight" className="py-20 px-6 max-w-5xl mx-auto grid md:grid-cols-12 gap-12 items-center">
        <motion.div 
          initial={{ opacity: 0, x: -40 }}
          whileInView={{ opacity: 1, x: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.6 }}
          className="md:col-span-7 space-y-6 text-left order-2 md:order-1"
        >
          <div className="h-9 w-9 rounded-lg bg-amber-50 text-amber-700 flex items-center justify-center">
            <Coins size={18} />
          </div>
          <h3 className="text-2xl md:text-3xl font-extrabold text-slate-800">Dynamic Market Intelligence</h3>
          <p className="text-slate-600 text-sm leading-relaxed">
            Wholesale mandi price rates vary widely across districts. Farmers lose out on major revenues because they lack real-time pricing transparency.
          </p>
          <p className="text-slate-600 text-sm leading-relaxed">
            Our market portal details active rates across regional grain mandis. Set target alerts on select crops, and receive SMS-style dashboard flags when prices hit your targets. 
          </p>
          <Link to="/register" className="inline-flex">
            <Button variant="outline" className="flex items-center gap-2">Check Local Mandis <ArrowRight size={14} /></Button>
          </Link>
        </motion.div>

        <motion.div 
          initial={{ opacity: 0, x: 40 }}
          whileInView={{ opacity: 1, x: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.6 }}
          className="md:col-span-5 flex justify-center order-1 md:order-2"
        >
          <div className="relative rounded-2xl overflow-hidden shadow-2xl border-4 border-slate-50 max-w-[340px]">
            <img src={marketImg} alt="Mandi price lists" className="w-full h-auto object-cover aspect-3/4" />
          </div>
        </motion.div>
      </section>

      {/* How It Works */}
      <section id="how-it-works" className="py-20 bg-slate-900 text-white px-6">
        <div className="max-w-5xl mx-auto space-y-12">
          <div className="text-center space-y-4">
            <h2 className="text-3xl font-bold tracking-tight">How It Works</h2>
            <p className="text-slate-400 max-w-md mx-auto text-xs">Configure your dashboard in three simple steps.</p>
          </div>

          <div className="grid md:grid-cols-3 gap-8 text-center">
            <div className="space-y-3">
              <div className="h-12 w-12 rounded-full bg-green-600 flex items-center justify-center text-lg font-bold mx-auto shadow-lg shadow-green-700/30">1</div>
              <h3 className="text-lg font-semibold">Map Farm Details</h3>
              <p className="text-xs text-slate-400 leading-relaxed">
                Add land locations and size. Configure soil type configurations to calibrate N-P-K recommendation formulas.
              </p>
            </div>
            <div className="space-y-3">
              <div className="h-12 w-12 rounded-full bg-green-600 flex items-center justify-center text-lg font-bold mx-auto shadow-lg shadow-green-700/30">2</div>
              <h3 className="text-lg font-semibold">Run Advisory Audits</h3>
              <p className="text-xs text-slate-400 leading-relaxed">
                Receive weather watering guides and daily crop advice that updates dynamically as plants advance through stages.
              </p>
            </div>
            <div className="space-y-3">
              <div className="h-12 w-12 rounded-full bg-green-600 flex items-center justify-center text-lg font-bold mx-auto shadow-lg shadow-green-700/30">3</div>
              <h3 className="text-lg font-semibold">Compare Sell Options</h3>
              <p className="text-xs text-slate-400 leading-relaxed">
                Input crop harvest volumes in the post-harvest tool to compare profits across local sales, regional freight, and cold storage.
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* Contact Section */}
      <section id="contact" className="py-20 max-w-4xl mx-auto px-6 space-y-12">
        <div className="text-center space-y-4">
          <h2 className="text-3xl font-black tracking-tight text-slate-800">Support & Contact</h2>
          <p className="text-slate-500 text-sm">Have questions about the platform or need support? Drop us a line.</p>
        </div>

        <div className="grid md:grid-cols-2 gap-8 items-start">
          <div className="space-y-6 text-slate-650 text-xs text-left">
            <div className="flex items-center gap-3">
              <Phone size={16} className="text-green-600" />
              <span>+91 98765 43210</span>
            </div>
            <div className="flex items-center gap-3">
              <Mail size={16} className="text-green-600" />
              <span>support@krishisakhi.org</span>
            </div>
            <div className="flex items-center gap-3">
              <UserCheck size={16} className="text-green-600" />
              <span>Admin Profile: admin@krishisakhi.org / admin123</span>
            </div>
          </div>

          <form onSubmit={handleSubmit} className="space-y-4 text-left">
            <div>
              <input
                type="text"
                required
                placeholder="Your Name"
                value={contactForm.name}
                onChange={(e) => setContactForm({ ...contactForm, name: e.target.value })}
                className="w-full rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm text-slate-900 focus:border-green-600 focus:outline-none"
              />
            </div>
            <div>
              <input
                type="email"
                required
                placeholder="Email Address"
                value={contactForm.email}
                onChange={(e) => setContactForm({ ...contactForm, email: e.target.value })}
                className="w-full rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm text-slate-900 focus:border-green-600 focus:outline-none"
              />
            </div>
            <div>
              <textarea
                required
                rows={4}
                placeholder="How can we help you?"
                value={contactForm.message}
                onChange={(e) => setContactForm({ ...contactForm, message: e.target.value })}
                className="w-full rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm text-slate-900 focus:border-green-600 focus:outline-none"
              />
            </div>
            <Button type="submit" className="w-full">Send Message</Button>
            
            {submitted && (
              <p className="text-xs text-green-600 font-semibold text-center mt-2">
                Thank you! Your message has been received. Our team will contact you shortly.
              </p>
            )}
          </form>
        </div>
      </section>

      {/* Footer */}
      <footer className="border-t border-slate-200 py-8 text-center text-xs text-slate-400 bg-white">
        <p>© 2026 KrishiSakhi agricultural support network. All rights reserved.</p>
      </footer>
    </div>
  );
}
